export const validicTrackerData = {
  measurements: { data: [] },
  nutrition: {
    data: [
      {
        category: "other",
        checksum: "7f571b280357a21dc0782de27b218625",
        created_at: "2022-09-29T08:12:57.551Z",
        deleted_at: null,
        end_time: "2022-09-22T22:59:59Z",
        id: "77ae0be4fd70749c745d1c30aea8bc2b",
        log_id: "2022-09-22",
        metrics: [
          {
            type: "energy_consumed",
            origin: "unknown",
            unit: "kcal",
            value: 0,
          },
          { type: "dietary_fiber", origin: "unknown", unit: "g", value: 0 },
          { type: "water", origin: "unknown", unit: "mL", value: 0 },
          { type: "carbohydrate", origin: "unknown", unit: "g", value: 0 },
          { type: "fat", origin: "unknown", unit: "g", value: 0 },
          { type: "protein", origin: "unknown", unit: "g", value: 0 },
          { type: "sodium", origin: "unknown", unit: "mg", value: 0 },
        ],
        name: "Unknown",
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-21T23:00:00Z",
        tags: [],
        type: "nutrition",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
      {
        category: "other",
        checksum: "e2740e51749ecc0b2a47f23afd2fd1f0",
        created_at: "2022-09-29T08:12:04.168Z",
        deleted_at: null,
        end_time: "2022-09-24T22:59:59Z",
        id: "d0fce7c15b8af9872b4064ca94239a1c",
        log_id: "2022-09-24",
        metrics: [
          {
            type: "energy_consumed",
            origin: "unknown",
            unit: "kcal",
            value: 0,
          },
          { type: "dietary_fiber", origin: "unknown", unit: "g", value: 0 },
          { type: "water", origin: "unknown", unit: "mL", value: 0 },
          { type: "carbohydrate", origin: "unknown", unit: "g", value: 0 },
          { type: "fat", origin: "unknown", unit: "g", value: 0 },
          { type: "protein", origin: "unknown", unit: "g", value: 0 },
          { type: "sodium", origin: "unknown", unit: "mg", value: 0 },
        ],
        name: "Unknown",
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-23T23:00:00Z",
        tags: [],
        type: "nutrition",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
      {
        category: "other",
        checksum: "19ccdc2d112a8433ad6a937a0348a6b0",
        created_at: "2022-09-29T08:22:35.945Z",
        deleted_at: null,
        end_time: "2022-09-26T22:59:59Z",
        id: "f0b2fef32fccd8e4d55097d7dc5b2570",
        log_id: "2022-09-26",
        metrics: [
          {
            type: "energy_consumed",
            origin: "unknown",
            unit: "kcal",
            value: 0,
          },
          { type: "dietary_fiber", origin: "unknown", unit: "g", value: 0 },
          { type: "water", origin: "unknown", unit: "mL", value: 0 },
          { type: "carbohydrate", origin: "unknown", unit: "g", value: 0 },
          { type: "fat", origin: "unknown", unit: "g", value: 0 },
          { type: "protein", origin: "unknown", unit: "g", value: 0 },
          { type: "sodium", origin: "unknown", unit: "mg", value: 0 },
        ],
        name: "Unknown",
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-25T23:00:00Z",
        tags: [],
        type: "nutrition",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
      {
        category: "other",
        checksum: "c7f21d9299dca49b38311f814b6f4de5",
        created_at: "2022-09-29T08:29:07.977Z",
        deleted_at: null,
        end_time: "2022-09-27T22:59:59Z",
        id: "c969a5042e3e55c558a9e005a909c209",
        log_id: "2022-09-27",
        metrics: [
          {
            type: "energy_consumed",
            origin: "unknown",
            unit: "kcal",
            value: 0,
          },
          { type: "dietary_fiber", origin: "unknown", unit: "g", value: 0 },
          { type: "water", origin: "unknown", unit: "mL", value: 0 },
          { type: "carbohydrate", origin: "unknown", unit: "g", value: 0 },
          { type: "fat", origin: "unknown", unit: "g", value: 0 },
          { type: "protein", origin: "unknown", unit: "g", value: 0 },
          { type: "sodium", origin: "unknown", unit: "mg", value: 0 },
        ],
        name: "Unknown",
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-26T23:00:00Z",
        tags: [],
        type: "nutrition",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
    ],
  },
  sleep: { data: [] },
  summary: {
    data: [
      {
        category: "daily",
        checksum: "b2fdeb9287948eeb86363891811b5d4c",
        created_at: "2022-09-29T08:26:12.508Z",
        deleted_at: null,
        end_time: "2022-09-24T22:59:59Z",
        id: "912c6ff4d8553024c7528b9359bfe484",
        log_id: "2022-09-24",
        metrics: [
          {
            type: "basal_energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "heart_rate_zone_very_low",
            origin: "device",
            unit: "s",
            value: 86400,
          },
          {
            type: "heart_rate_zone_low",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_medium",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_high",
            origin: "device",
            unit: "s",
            value: 0,
          },
        ],
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-23T23:00:00Z",
        tags: [],
        type: "summary",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
      {
        category: "daily",
        checksum: "2a7d37010dee0bcdb5ba4a5fe21c4f7d",
        created_at: "2022-09-29T08:18:36.525Z",
        deleted_at: null,
        end_time: "2022-09-25T22:59:59Z",
        id: "3e8dc543cb4b75c707ecd59cc7fcb024",
        log_id: "2022-09-25",
        metrics: [
          {
            type: "basal_energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "heart_rate_zone_very_low",
            origin: "device",
            unit: "s",
            value: 86400,
          },
          {
            type: "heart_rate_zone_low",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_medium",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_high",
            origin: "device",
            unit: "s",
            value: 0,
          },
        ],
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-24T23:00:00Z",
        tags: [],
        type: "summary",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
      {
        category: "daily",
        checksum: "4e7be3dd1efd67afe558c9cd3ebfdb53",
        created_at: "2022-09-29T08:26:12.525Z",
        deleted_at: null,
        end_time: "2022-09-28T22:59:59Z",
        id: "2348edf50489301e610f99482e90b71e",
        log_id: "2022-09-28",
        metrics: [
          {
            type: "basal_energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "energy_burned",
            origin: "device",
            unit: "kcal",
            value: 1771,
          },
          {
            type: "heart_rate_zone_very_low",
            origin: "device",
            unit: "s",
            value: 86400,
          },
          {
            type: "heart_rate_zone_low",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_medium",
            origin: "device",
            unit: "s",
            value: 0,
          },
          {
            type: "heart_rate_zone_high",
            origin: "device",
            unit: "s",
            value: 0,
          },
        ],
        offset_origin: "profile",
        segments: [],
        source: { type: "fitbit", device: null },
        start_time: "2022-09-27T23:00:00Z",
        tags: [],
        type: "summary",
        user: {
          organization_id: "5e8b81d79ad68b00b03b8cc0",
          user_id: "63344950e9e45e0001ca01f8",
          uid: "6334400fc3968d355cf6c55a",
        },
        user_notes: [],
        utc_offset: 3600,
        version: "1.0",
      },
    ],
  },
  workout: { data: [] },
  intraday: { data: [] },
};

export const dBTrackerData = {
  summary: { steps: [], distance: [], energyBurned: [], restingHeartRate: [] },
  circulatoryHealth: {
    pulse: [],
    bloodPressure: { systolic: [], diastolic: [] },
    heartRate: [],
    bodyTemperature: [],
  },
  respiratoryHealth: {
    sp02: [],
    smokedLastSevenDays: [],
    respirationRate: [],
    peakExpiratoryFlow: [],
    degreeOfBreathlessness: [],
  },
  bodyMeasurements: { weight: [], waistCircumference: [], height: [], bmi: [] },
  myDiabetes: {
    bloodKetone: [],
    hbA1c: { measurements: [], recordedInLastTwelveMonths: {} },
    bloodGlucose: [],
    totalCholesterol: [],
    ldlCholesterol: [],
    hdlCholesterol: [],
    retinalScanInLastTwelveMonths: false,
    footScanInLastTwelveMonths: false,
    insulin: [],
  },
  myHypertension: { bloodSodium: [] },
  myHeartHealth: {
    bloodEGFR: [],
    bloodCreatinine: [],
    daysOfBreathlessness: [],
    daysOfSwollenAnkles: [],
    daysOfChestPain: [],
  },
  stopSmoking: {
    cigarettesPerDay: [],
    lastCigaretteTimeDate: [],
    usingNicotineReplacement: [],
    morningTimeToFirstCigarette: [],
    startDateOfStopSmokingProgram: "N/A",
  },
  myPain: {
    numDaysWithMildModeratePain: [],
    numDaysSeverePain: [],
    degreeOfPain: [],
  },
  drinkLess: { numAlcoholUnits: [], hadADrinkToday: [], alcoholFreeDays: [] },
  myMood: { positiveDaysThisWeek: [], moodScale: [] },
  _id: "6334400e8e079ac7c91fe592",
  PASID: "70875",
  __v: 0,
};
